from bbo.algorithms.sampling.random import RandomDesigner
from bbo.algorithms.search.local_search import LocalSearchDesigner
from bbo.algorithms.search.grid import GridSearchDesigner
from bbo.algorithms.evolution.cmaes import CMAESDesigner
from bbo.algorithms.evolution.nsgaii import NSGAIIDesigner
from bbo.algorithms.evolution.regularized_evolution import RegularizedEvolutionDesigner
from bbo.algorithms.evolution.pso import PSODesigner
from bbo.algorithms.bo.bo import BODesigner
from bbo.algorithms.ensemble.chain import ChainDesigner